apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-sites
  labels:
    volume: local-sites
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/developer/Sites"
